repos:
  - repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: lint-script
      name: lint-script
      entry: ./tasks/lint.sh
      language: script
      types: [python]