repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
  - id: lint-script
    name: lint-script
    entry: ./tasks/lint.sh
    language: script
    types: [python]
  - id: test-func-script
    name: test-functionality-script
    entry: ./tasks/test_functionality.sh
    language: script
- repo: https://github.com/ryanrhee/shellcheck-py
  rev: v0.7.1.1
  hooks: 
  - id: shellcheck