name: Cloud Run Continous Deployment

on:
  push:
    branches: [master]

env:
  PROJECT_ID: ${{ secrets.GCP_SERVICE_ACCOUNT.project_id }}
  RUN_REGION: northamerica-northeast1
  SERVICE_NAME: ${{ secrets.GCP_SERVICE_ACCOUNT.project_id }}
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Master Branch
        uses: actions/checkout@master
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Configure GCP Credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "313.0.1"
          project_id: ${{ secrets.GCP_SERVICE_ACCOUNT.project_id }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT.private_key }}
          export_default_credentials: true
      - name: Setup Conda Squalifier Environment
        shell: bash -l {0}
        run: |
          conda init bash
          conda env create 
          conda activate squalifier
          pip-sync requirements.txt requirements-dev.txt --find-links https://download.pytorch.org/whl/torch_stable.html
        env:
          PYTHONPATH: .
      - name: Build Docker API Image
        shell: bash -l {0}
        run: |
          conda activate squalifier
          ./task/build_api_docker.sh
      - name: Push Image to GCP Container Registry
        shell: bash -l {0}
        run: |
          ./task/push_docker_to_gcp.sh
      - name: Deploy Image to GCP
        shell: bash -l {0}
        run: ! ./task/deploy_docker_image.sh
