name: Python Continous Integration for Model Predictions

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Setup Conda Squalifier Environment
        shell: bash -l {0}
        run: |
          conda init bash
          conda env create 
          conda activate squalifier
          pip-sync requirements.txt requirements-dev.txt --find-links https://download.pytorch.org/whl/torch_stable.html
      - run: export PYTHONPATH=.
      - name: Run Functionality Tests
        shell: bash -l {0}
        run: ./tasks/test_functionality.sh
